spring:
    main:
        show_banner: off
    application:
        name: mvc-app
    profiles:
        active: local-dev

---

spring.profiles: local-dev

spring:
    jpa.show-sql: true
    h2.console.settings.web-allow-others: true
    datasource.url: jdbc:h2:./db/dev/bin;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS WEBAPP\;SET SCHEMA WEBAPP
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update
server:
    port: 88

---

spring.profiles: prod

spring:
    jpa.show-sql: false
    h2.console.settings.web-allow-others: true
    datasource.url: jdbc:h2:./db/prod/bin;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS WEBAPP\;SET SCHEMA WEBAPP
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update
server:
    port: 8888